export class Customer {
        // CustomerID: number;
        // CustNum: string;
        // Prefix: string;
        // FirstName: string;
        // LastName: string;
        // AddressLine1: string;
        // AddressLine2: string;
        // City: string;
        // PostalCode: string;
        // StateID: number;
        // CountryID: number;
        // County: string;
        // RegionID: string;
        // Cabin: string;
        // Folio: string;
        // BidNum: number;
        // BidDate: Date;
        // CompanyName: string;
        // TaxID: string;
        // PhoneCode: string;
        // HomePhone: string;
        // WorkPhone: string;
        // LeadCode: string;
        // Email: string;
        // SessionNum: number;
        // IsExisting: boolean;
        // LastPostalCode: string;
        // IsPrimaryAddress: boolean;
        // PaymentTypeCode: string;
        // CreditCardNumber: string;
        // CreditCardExpire: string;
        // PWCCOpenToBuy: number;
        // PWCCCall: boolean;
        // HistoricalCustNum: string;
        // FirstNameAdditional: string;
        // LastNameAdditional: string;
        // ModifiedBy: string;
        // ModifiedDate: Date;
        // CreatedBy: string;
        // CreatedDate: Date;
        // DeletedBy: string;
        // DeletedDate: Date;
        // //calculated fields
        // HasInvoice: boolean;
        // PaymentCount: number; 

      
}